baseURL: "https://jaydenevett.cv" 
title: Jayden Evett
theme: PaperMod

enableInlineShortcodes: true
enableRobotsTXT: true
pagination:
  pagerSize: 20

taxonomies:
    tag: tags

menu:
    main:
        - name: Publications
          url: publicaitons/
          weight: 1 
        - name: PhD thesis
          url: https://hdl.handle.net/1885/733750511
          weight: 2
        - name: Master's thesis
          url: https://hdl.handle.net/1885/733713482
          weight: 3 

params:
    description: "This website includes Jayden Evett's writing, including his theses, and contact information."
    author: Jayden Evett
    DateFormat: "January 2025"
    defaultTheme: light
    hideFooter: true
    disableThemeToggle: true
    ShowShareButtons: false
    ShowReadingTime: false
    disableSpecial1stPost: true
    disableAnchoredHeadings: true
    ShowPostNavLinks: false
    ShowBreadCrumbs: false
    ShowCodeCopyButtons: true
    ShowAllPagesInArchive: false
    MainSections: ["books","courses","papers","data"]
    ShowToc: false
    disableScrollToTop: true
    TocOpen: true
    ShowWordCount: false
    UseHugoToc: true
    comments: false
    math: true
    profileMode:
          enabled: true
          title: Jayden Evett
          subtitle: "I am giant turd"
          imageUrl: "profilepicture.png"
          imageWidth: 160
          imageHeight: 160
          buttons:
            - name: Publications
              url: publications/
            - name: PhD thesis
              url: https://hdl.handle.net/1885/733750511
            - name: Master's thesis
              url: https://hdl.handle.net/1885/733713482

    socialIcons:
        - name: CV
          url: cv.pdf
        - name: Email
          url: mailto:hello@jaydenevett.cv
        - name: LinkedIn
          url: https://www.linkedin.com/in/jaydenevett/
        - name: Google Scholar
          url: https://scholar.google.com/citations?user=ah64k5kAAAAJ&hl
          

    assets:
        disableScrollBarStyle: true
    cover:
        hiddenInList: false
        hiddenInSingle: true
    label:
      text: "Jayden Evett"
      icon: favicon.ico
      iconHeight: 18

markup:
    goldmark:
        renderer:
            unsafe: true
    highlight:
        guessSyntax: true
        style: autumn 
    tableOfContents:
        endLevel: 2
        ordered: false
        startLevel: 2
